steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/main', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/main']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ["run", "deploy", "mainsvc", "--image", "gcr.io/${PROJECT_ID}/main", "--port", "80", "--platform", "managed", "--region","us-central1","--allow-unauthenticated"]
  - name: 'gcr.io/cloud-builders/git'
    args: ['tag','v0.2']
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args: ['-c','cat .git/config']
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args: ['-c','ls -lart']
  - name: 'gcr.io/cloud-builders/git'
    args: ['config', '--global', 'test.foo', 'bar']
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args: ['-c', 'git config --global --get test.foo | grep ^bar$']
  - name: 'gcr.io/cloud-builders/git'
    args: ['push','--tags','https://github.com/Buddhiprakash-jain/Extra_task_repo.git']



  
