steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/main', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/main']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ["run", "deploy", "mainsvc", "--image", "gcr.io/${PROJECT_ID}/main", "--port", "80", "--platform", "managed", "--region","us-central1","--allow-unauthenticated"]
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone','https://github.com/Buddhiprakash-jain/Extra_task_repo.git']
  - name: 'gcr.io/cloud-builders/git'
    args: ['remote', 'set-url', 'origin', 'https://{buddhijainmadhorajpura72@gamil.com}:{Buddhi8290@}@github.com/{buddhijainmadhorajpura72@gamil.com}/project.git']
  - name: 'gcr.io/cloud-builders/git'
    args: ['push' ,'--set-upstream' ,'origin' ,'master']
