steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/dev', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dev']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ["run", "deploy", "devsvc", "--image", "gcr.io/${PROJECT_ID}/dev", "--port", "80", "--platform", "managed", "--region","us-central1","--allow-unauthenticated"]
