steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/main', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/main']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ["run", "deploy", "mainsvc", "--image", "gcr.io/${PROJECT_ID}/main", "--port", "80", "--platform", "managed", "--region","us-central1","--allow-unauthenticated"]
  - name: 'gcr.io/cloud-builders/git'
    args: ['tag', 'v0.2','https://github.com/Buddhiprakash-jain/Extra_task_repo/tree/master']
  - name: 'gcr.io/cloud-builders/git'
    args: ['push', 'origin', '--tags']
